### ISSUE TITLE
Style Partners Section 

### ISSUE THREAD

**Issue by Evavic44** [DevsHelpDevs/coming_soon_web#29]
Style partners section to look similar to the website template on Figma.

**Comment by biggaji** [comment]
Please can you send a screenshot of it in the figma file, i can view it from here

**Comment by Evavic44** [comment]
Okay. Will do that.

**Comment by Evavic44** [comment]
![partners-section](https://user-images.githubusercontent.com/62628408/116076222-db9b8700-a68b-11eb-84f8-3cd72e356c8d.png)
Here is what the partners link is supposed to look like.
- [ ] Reduce link width and height
- [ ] Add round borders to the partner links

**Comment by biggaji** [comment]
Please let me confirm from he ui/ux designer.

**Comment by biggaji** [comment]
@escamoteur said it is okay without the rounded corners!
Check the #design

**Comment by escamoteur** [comment]
let's put it this way, I would like to see how it looks like with the logos in it

**Comment by Evavic44** [comment]
It's not a necessary change, I just thought we wanted it to look like the Figma design. But here it is though 👇🏾  Could be made closer than that also.
![partner-section](https://user-images.githubusercontent.com/62628408/116277332-4678bb00-a77d-11eb-9795-3030f5b58c67.png)
